{"unique_id": "30355b13118170dbbfa1e4173acf59b373d43f545afda3da59702a4a73d3674e", "model_name": "enhanced_model", "prediction": "Prediction failed: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: connect: Connection refused (61)\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer ipv6:%5B::1%5D:50050 {grpc_message:\"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50051: Failed to connect to remote host: connect: Connection refused (61)\", grpc_status:14, created_time:\"2024-10-27T04:24:46.330732+00:00\"}\"\n>", "timestamp": 1730003086.3310778, "image_hash": "b5a488a42604fa0141d4764fcba78c61e9a0981e295e954a76779ac48143d90a", "attestation_hash": "32823d339b596d6f9db7ab47e306e5cd2ebbcdbaf5aef53e393caa62be0fe5dd"}